name: Deploy Docs to GitHub Pages

on:
    push:
        branches:
            - develop
        paths:
            - 'apps/docs/**'
            - '.github/workflows/deploy-docs.yaml'

    pull_request:
        branches:
            - develop

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: pnpm/action-setup@v4
                name: Install pnpm
                with:
                    run_install: false

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: 'pnpm'

            -   name: Install dependencies
                run: pnpm install

            -   name: Build Project
                run: pnpm build:docs

            -   name: Deploy to GitHub Pages
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: apps/docs/build
