name: Deploy Docs to GitHub Pages

on:
    push:
        branches:
            - develop
        paths:
            - 'apps/docs/**'
            - '.github/workflows/deploy-docs.yaml'

    pull_request:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: pnpm/action-setup@v4
                name: Install pnpm
                with:
                    run_install: false

            -   name: Install Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: 'pnpm'

            -   name: Install dependencies
                run: pnpm install

            -   name: Build Project
                run: pnpm build:docs

            -   name: Upload Build Artifact
                uses: actions/upload-pages-artifact@v3
                with:
                    path: apps/doc/build

    deploy:
        name: Deploy to GitHub Pages
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
